development:

  publishing_s3_bucket: 'assets.getuniboard.com'
  publishing_s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  publishing_s3_secret_access_key: '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'

  publishing_s3_document_endpoint: 'http://assets.getuniboard.com'

test:

  publishing_s3_bucket: 'assets.getuniboard.com'
  publishing_s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  publishing_s3_secret_access_key: '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'

  publishing_s3_document_endpoint: 'http://assets.getuniboard.com'
  
production:

  publishing_s3_bucket: 'assets.getuniboard.com'
  publishing_s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  publishing_s3_secret_access_key: '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'

  publishing_s3_document_endpoint: 'http://assets.getuniboard.com'

