development:
  documents_s3_bucket: 'assets.getuniboard.com'
  documents_s3_publishing_endpoint: 'http://assets.getuniboard.com'
  documents_s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  documents_s3_secret_access_key: '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'

test:
  documents_s3_bucket: 'assets.getuniboard.com'
  documents_s3_publishing_endpoint: 'http://assets.getuniboard.com'
  documents_s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  documents_s3_secret_access_key: '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'
  
production:

  documents_s3_bucket: 'assets.getuniboard.com'
  documents_s3_publishing_endpoint: 'http://assets.getuniboard.com'
  documents_s3_access_key_id: 'AKIAJSQQ2RDIXG2UOZ5Q'
  documents_s3_secret_access_key: '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'